  
kind: Namespace
apiVersion: v1
metadata:
  name: gruntwork
  labels:
    name: gruntwork
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-docker
  namespace: gruntwork
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app-docker
  template:
    metadata:
      name: sample-app-docker
      labels:
        app: sample-app-docker
    spec:
      containers:
      - name: sample-app-docker
        image: omria/sample-app-docker:$IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"        
---
apiVersion: v1
kind: Service 
metadata:
  name: sample-app-docker-svc
  namespace: gruntwork
  labels:
    app: sample-app-docker
spec:
  selector:
    app: sample-app-docker
  type: ClusterIP
  ports:
  - protocol: TCP  
    port: 80
    targetPort: 80